apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-example8-deployment
 labels:
  app: my-example8
spec:
 selector:
  matchLabels:
   app: my-example8
 replicas: 2
 template:
  metadata:
   labels:
    app: my-example8
  spec:
   containers:
   - name: my-example8
     image: majrul/my-example8
     ports:
      - containerPort: 8080
 