#FROM openjdk:17-alpine
FROM openjdk
COPY App.class .
CMD java App

#Alternative
#FROM ubuntu
#RUN apt update
#RUN apt install -y openjdk-17-jre-headless
#COPY HelloWorld.class .
#CMD java HelloWorld
